### Recuperar todos los libros
GET http://localhost:4321/books

### Recuperar un libro
GET http://localhost:4321/books/1

### Crear un libro
POST https://express-api-rest.onrender.com/books
Content-Type: application/json

 {
    "title": "El señor de los anillos: Las Dos Torres",
    "author": "J. R. R. Tolkien",
    "photo": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.esquire.com%2Fes%2Factualidad%2Flibros%2Fa40877076%2Fsenor-de-los-anillos-orden-libros-tolkien%2F&psig=AOvVaw0hUdNiYaAhcCwnstoHMNLq&ust=1714927319708000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCMjYt6C49IUDFQAAAAAdAAAAABAX"
}

### Actualizar un elemento de un libro.
PUT http://localhost:4321/books/im82p5udXJtMAUE95gTK
Content-Type: application/json

{
    "title":"El señor de los anillos: La Comunidad del Anillo"
}

### Borrar un libro
DELETE http://localhost:4321/books/1